### PR TITLE
render code

### LINKED ISSUE #245: Code is not displaying, Informatik somewhat unusable
Subject Informatik uses code-blocks from the old editor, e.g.
https://de.serlo.org/informatik/algorithmen/robot-karol/wiederholungen

Currently those are not displayed in the new design, which makes a lot of content currently unusable.
@yolo-bird do you know if and when those will be converted?

---

Also there is a course that uses inline-code, which is currently not supported in the new editor:
https://de.serlo.org/informatik/internet-dinge-circuitpython/anf%C3%A4ngerkurse/grundlagen-1/mu-starten
@yolo-bird who could rework this one?

### PR DESCRIPTION
**Pull request by Entkenntnis**
fixes #245

### CODE REVIEW

**Comment by elbotho** [comment]
okay @Entkenntnis basic styling for code blocks is done. 
I ran into a problem with wrapping again. The only way I see to differentiate between inline code and blocks is to check the parent (or forward that information to the component). 

If it's a `<p>` it should render inline (without `<pre>`) otherwise it breaks the layout and also results in a warning
>Warning: Expected server HTML to contain a matching pre> in p>.

Do you have an idea how we could forward that?

**Comment by Entkenntnis** [comment]
@elbotho Can you give me the links to the corresponding pages? Haven't tested it much, yet - we can fix many html problems by tweaking the converter ... and probably adding a new element type for inline code

**Comment by elbotho** [comment]
It's [here](http://localhost:3000/informatik/internet-dinge-circuitpython/anf%C3%A4ngerkurse/grundlagen-1/erstes-programm) but this is not currently supported in the new editor, is not widely used and we should not put a lot of work into it!

If you don't have a quick solution I'd be okay with a dirty but well documented global css hack for that.

**Comment by Entkenntnis** [comment]
Quickfix added: ignoring inline code

**Pull request merged**
