### PR TITLE
feat: add maintenance banner

### PR DESCRIPTION
**Pull request by hugotiburtino**

### CODE REVIEW

**Comment by hugotiburtino** [comment]
@elbotho could you please fix the banner, so that it doesn't overlay the donation button?

**Comment by elbotho** [comment]
@hugotiburtino I made some changes.
It's probably easier to deploy to prod directly and I would probably deploy this maybe tonight.

**Comment by hugotiburtino** [comment]
@elbotho 
sure and thanks!

**Comment by elbotho** [comment]
direct deploy in https://github.com/serlo/frontend/pull/2776

**Pull request closed without merging**
