### PR TITLE
Remove support to wikimedia videos due to data privacy reasons

### PR DESCRIPTION
**Pull request by hugotiburtino**
[Demo](https://frontend-git-remove-wikimedia-video-serlo.vercel.app/___editor_preview?state=%7B%22plugin%22%3A%22rows%22%2C%22state%22%3A%5B%7B%22plugin%22%3A%22video%22%2C%22state%22%3A%7B%22src%22%3A%22https%3A%2F%2Fstorage.googleapis.com%2Fassets.serlo.org%2Fwikimedia%2FMfnf-linear-skalar2.webm%22%2C%22alt%22%3A%22%22%7D%2C%22id%22%3A%224adb614d-f153-4c0b-9625-907493d5d839%22%7D%5D%7D)

### CODE REVIEW

**Review by elbotho — APPROVED** [review]
👍 thank you.

Follow ups (not urgent at all):
- remove from consent (frontend)
- remove from preview (cf-worker)


(preview build fail should be a temporary problem, no blocker)

**Comment by hugotiburtino** [comment]
Sorry, I've noticed a minor bug. I'll make it a draft and let you know when it is ok again

**Comment by hugotiburtino** [comment]
Now, it shows the video preview directly (No message "Video abspielen von....").

You can test at https://frontend-git-remove-wikimedia-video-serlo.vercel.app/___editor_preview with 
https://storage.googleapis.com/assets.serlo.org/wikimedia/Mfnf-linear-skalar2.webm

**Review by elbotho — APPROVED** [review]
Thank you!
This could in theory affect other editor integrations, but since it's so seldomly used I think the risk is small enough.

**Pull request merged**
