### PR TITLE
edit comments

### LINKED ISSUE #2062: thread: add edit feature
User should be allowed to edit their own comment.
When the current viewer is the comment author, it should appear a pencil icon or any sort of info that they can edit it.

Blockers:
- [x] https://github.com/serlo/api.serlo.org/issues/762
- [x] https://github.com/serlo/database-layer/issues/351

### PR DESCRIPTION
**Pull request by Entkenntnis**
TODO:

- [x] i18n strings
- [x] styling
- [x] handle error while submitting
- [x] clean up code

### CODE REVIEW

**Comment by Entkenntnis** [comment]
next up: create mutation and refresh cache

**Comment by hugotiburtino** [comment]
Sorry I should have written it in the issue.
- [x] No need to show _edit_ button if the comment is trashed
- [x] No need to show _edit_ button if the comment is archived
(editing them won't work anyway)

**Comment by Entkenntnis** [comment]
thanks for the clearification and no problem here, that's part of the process and I'm happy about feedback, I will check for this

**Comment by Entkenntnis** [comment]
@elbotho I have done some UX tweaks, can you review it? Some questions:

- I have added an abort-button, but I'm not super happy with the positioning.
- I have changed the background color to white so users can distinguish creating/writing comments
- Thread bearbeiten / Kommentar bearbeiten sound a bit verbose, maybe using "Bearbeiten" vor both is sufficient?

If the UI is complete, I will finish this up.

**Comment by Entkenntnis** [comment]
testing on staging can be started

**Pull request merged**
