### PR TITLE
Add "Not-Equal-To" sign to equations plugin

### PR DESCRIPTION
**Pull request by kulla**
Fixes https://serlo.slack.com/archives/C0BMSC431/p1661763605954029

### CODE REVIEW

**Review by inyono — DISMISSED** [review]

**Comment by elbotho** [comment]
@kulla this is fine for the edtr, but I think this would not render in the frontend atm.

See: https://github.com/serlo/frontend/blob/staging/src/components/content/equations.tsx

**Review by elbotho — CHANGES_REQUESTED** [review]
see comment.

**Comment by elbotho** [comment]
@kulla ping me if I should take over

**Comment by kulla** [comment]
@elbotho Ready to be merged (and you can take over)

**Pull request merged**
