### PR TITLE
fix(text-editor): pasting image and geogebra urls creates plugins again

### PR DESCRIPTION
**Pull request by elbotho**

### CODE REVIEW

**Review by hejtful — APPROVED** [review]

**Review by Entkenntnis — APPROVED** [review]
Changes look good - haven't tested it manually though.

(maybe a candidate for a e2e test, because this feature seems to break every now and then)

**Comment by elbotho** [comment]
yeah, I added it to our testing document for now. If @yanncloud is done with the current tests he could add them maybe.

**Comment by hejtful** [comment]
Nice, I had no idea this was ever a feature or even possible

**Comment by elbotho** [comment]
Found it in the old edtr-io text plugin, but it was as bit less obvious there :)

**Pull request merged**
