### PR TITLE
deploy: add maintenance banner for 2023-10-06

### PR DESCRIPTION
**Pull request by hugotiburtino**

### CODE REVIEW

**Review by elbotho — APPROVED** [review]

**Comment by hugotiburtino** [comment]
@elbotho it goes to `staging` or directly to `prod`? 
Anyways, could you take the deployment over?

**Review by Entkenntnis — APPROVED** [review]
good old friend :)

**Comment by elbotho** [comment]
>@elbotho it goes to staging or directly to prod?
Anyways, could you take the deployment over?

tonight maybe?

**Comment by Entkenntnis** [comment]
I would deploy today late afternoon / evening (because I have another bug fix) and can take this over

**Comment by Entkenntnis** [comment]
not actually deployed yet (I have canceled the production build, was not intended for production 🙈 ), will open a new Deployment-PR for it

**Pull request merged**
