### PR TITLE
fix license undefined error

### PR DESCRIPTION
**Pull request by elbotho**
for some types (or on an inconsistency server side, not sure) license info can be undefined.

### CODE REVIEW

**Comment by inyono** [comment]
Can you give some example UUIDs? IMHO, this shouldn't happen...

**Comment by elbotho** [comment]
@inyono Well ok then I'll fix it properly ;) 
We just did not fetch the license data for `GroupedExerciseRevision` because we usually don't display license info on revisions.

**Comment by elbotho** [comment]
example url https://frontend-git-fix-license-error-serlo.vercel.app/entity/repository/compare/0/3936
The `0` in the url should be gone in staging/production I think.

**Comment by inyono** [comment]
> example url https://frontend-git-fix-license-error-serlo.vercel.app/entity/repository/compare/0/3936
> The `0` in the url should be gone in staging/production I think.

That's an independent frontend issue. Not sure where you get the `0` from but this only happens on frontend.serlo.org (which isn't handled via CF Worker redirects).

**Comment by Entkenntnis** [comment]
Thank!

**Pull request merged**
