### PR TITLE
Some code documentation comments

### PR DESCRIPTION
**Pull request by LarsTheGlidingSquirrel**
## Before
The component name `DocumentEditor` can be very confusing: 
- It is below `InnerDocument`, `Editor` and `SubDocumentEditor` in the component hierarchy. 
- Is sounds like much but is just a container for plugin editor, toolbar and settings. 

## Changes
- Add code documentation comments

### CODE REVIEW

**Review by Entkenntnis — APPROVED** [review]
👍 definitively more expression :)

**Comment by elbotho** [comment]
I like the change, thank you. 
Since @hejtful and me are working on the Plugin Toolbar right now over at https://github.com/serlo/frontend/tree/feat/plugin-toolbar maybe we will do the merging, okay?

**Comment by LarsTheGlidingSquirrel** [comment]
> Since @hejtful and me are working on the Plugin Toolbar right now over at https://github.com/serlo/frontend/tree/feat/plugin-toolbar maybe we will do the merging, okay?

@elbotho Alright!

**Comment by hejtful** [comment]
What do you think about `PluginSettings`, instead of `SettingsAndToolbar`?

For me, `SettingsAndToolbar` is quite general, and without context I'd guess that it means "editor settings". And as Botho mentioned, plugin toolbar will probably be moved out of this component soon.

**Comment by LarsTheGlidingSquirrel** [comment]
> What do you think about PluginSettings, instead of SettingsAndToolbar?
For me, SettingsAndToolbar is quite general, and without context I'd guess that it means "editor settings". And as Botho mentioned, plugin toolbar will probably be moved out of this component soon.

@hejtful Having one component called `PluginToolbar` and one `PluginSettings` would be even better! If you are working on it right now, do you want to continue with this pull request? Or should I make the change?

**Comment by hejtful** [comment]
> Having one component called PluginToolbar and one PluginSettings would be even better! If you are working on it right now, do you want to continue with this pull request? Or should I make the change?

I can do it after we finish with the PluginToolbar, but it won't be so soon. Maybe we can keep this PR open as a reminder, and in case something changes with the PluginToolbar, I guess we can then merge this PR as is. What do you think?

**Comment by LarsTheGlidingSquirrel** [comment]
> I can do it after we finish with the PluginToolbar, but it won't be so soon. Maybe we can keep this PR open as a reminder, and in case something changes with the PluginToolbar, I guess we can then merge this PR as is. What do you think?

I reverted the renaming and added a TODO comment instead.

**Comment by elbotho** [comment]
@LarsTheGlidingSquirrel little thing: We use ` TODO: … ` not `@TODO`
This way they also get picked up by eslint.

**Comment by LarsTheGlidingSquirrel** [comment]
> @LarsTheGlidingSquirrel little thing: We use TODO: … not @TODO
This way they also get picked up by eslint.

Ah, good to know. I'll change them.

**Pull request merged**
