### PR TITLE
Breadcrumbs: shorter and smaller

### LINKED ISSUE #11: breadcrumbs styling when path is very long
grafik

Ideas how to prevent this?

### PR DESCRIPTION
**Pull request by elbotho**
fixes #11
- smaller font size
- `…` when more than 4 items

### CODE REVIEW

**Comment by Entkenntnis** [comment]
Overlong title is overflowing page on mobile: https://frontend-git-fork-elbotho-breadcrumbs-shortened.dal123.now.sh/27801

**Comment by Entkenntnis** [comment]
And the back button links to the same page again

**Comment by elbotho** [comment]
> Overlong title is overflowing page on mobile
Nice find. Will try to find a nice solution for line breaks.

> And the back button links to the same page again
Hm it's the page link instead of the folder so something went quite wrong, but the link is correct ;)
(solved it)

**Comment by elbotho** [comment]
Please check again.

**Comment by Entkenntnis** [comment]
Thank you, both issues are fixed!

**Pull request merged**
