### PR TITLE
fix(image-plugin-redesign): fix url regex to be case insensitive

### PR DESCRIPTION
**Pull request by shn-srl**

### CODE REVIEW

**Review by elbotho — APPROVED** [review]
👍

**Comment by elbotho** [comment]
gOoD jOB

**Review by hejtful — APPROVED** [review]
Bug fixed 👍 

Note: When you edit the URL, just do a backspace and the URL is invalid. This makes the modal disappear and the empty Image plugin state is shown. But, the URL field is not focused any more. This seems not really optimal from UX perspective.

**Comment by shn-srl** [comment]
> Bug fixed 👍
> 
> Note: When you edit the URL, just do a backspace and the URL is invalid. This makes the modal disappear and the empty Image plugin state is shown. But, the URL field is not focused any more. This seems not really optimal from UX perspective.

Will discuss the UX of this with Gregor tomorrow

**Pull request merged**
