### PR TITLE
refactor(workspaces): e2e-test as workspace

### PR DESCRIPTION
**Pull request by elbotho**
https://github.com/serlo/frontend-e2e-tests -> `apps/e2e-tests`

### CODE REVIEW

**Comment by elbotho** [comment]
@Entkenntnis do you know why playwright ran without `yarn playwright install` in the old GitHub Action?

**Comment by Entkenntnis** [comment]
it just worked 🤷‍♀️ probably run automatically.

Anyways - I thought about *not* adding it as workspace, but simple into a folder like `./e2e-tests`, reasons: downloading browsers is quite heavy and we don't need it for the frontend + there is no coupling with existing code at all, so I don't see advantages of using it as a yarn workspace (maybe prettier can be shared, but that's only nice to have)

Thoughts?

**Comment by elbotho** [comment]
(on slack)

**Comment by elbotho** [comment]
tests fail right now but the output is exactly the same as on staging.

**Review by hejtful — APPROVED** [review]

**Comment by elbotho** [comment]
@Entkenntnis I don't really get why the tests are failing here. Any idea?

**Comment by Entkenntnis** [comment]
maybe login is not possible because it's not staging?

**Pull request closed without merging**
