### PR TITLE
feat(editor): add simple tooltips (text-toolbar and some other icon buttons)

### PR DESCRIPTION
**Pull request by elbotho**
[test here](https://frontend-git-editor-tooltips-first-go-serlo.vercel.app/entity/repository/add-revision/1555)

image

### CODE REVIEW

**Review by hejtful — APPROVED** [review]
Looks great!

**Review by Entkenntnis — APPROVED** [review]
thanks, changes look good

**Comment by Entkenntnis** [comment]
minor gotcha: due to known drag'n'drop-issue, the drag-preview also includes the tooltip.

**Comment by elbotho** [comment]
> minor gotcha: due to known drag'n'drop-issue, the drag-preview also includes the tooltip.

Persistent tool explanation. That's a feature not a bug ;)

**Pull request merged**
