### PR TITLE
chore(packages): upgrade nextjs

### PR DESCRIPTION
**Pull request by elbotho**
current version of nextjs should solve those two:
https://serlo.sentry.io/issues/4434444000/?project=5206333&query=&referrer=project-issue-stream
https://serlo.sentry.io/issues/4434439753/?project=5206333&query=&referrer=project-issue-stream

I thought they only affect reporting but it seems for some older browsers rendering the pages actually fails.

### CODE REVIEW

**Review by Entkenntnis — APPROVED** [review]
thanks, you can merge into staging and run the tests against it

**Comment by elbotho** [comment]
I will as soon as we figured out the failing test on staging ;)

**Comment by elbotho** [comment]
Thank you https://github.com/serlo/frontend-e2e-tests/commit/fb9b664a733d27d3b5b3097f4de27d4c7f8fb480 :)

**Comment by Entkenntnis** [comment]
I fixed it with https://github.com/serlo/frontend-e2e-tests/commit/fb9b664a733d27d3b5b3097f4de27d4c7f8fb480 :)

**Comment by elbotho** [comment]
image
😄

**Comment by elbotho** [comment]
there is now a hydration error on staging in the equations plugin. Investigating…

**Pull request merged**
