### PR TITLE
move toast-notice to module, remove context

### PR DESCRIPTION
**Pull request by elbotho**
Note: @Entkenntnis Last commit moves the instance data to a global variable instead of a JSON. 
This way we can access it pretty nicely with `window.__CLIENT_INSTANCE_DATA__` in the frontent-client-base.
Looks a bit neater, but can also revert if you prefer

### CODE REVIEW

**Review by Entkenntnis — CHANGES_REQUESTED** [review]
I'll wait for this after current deployment. Bundle size for slug went up by 26kb -> isServer seems to break server-side detection.

**Comment by elbotho** [comment]
> isServer seems to break server-side detection

I knew there had to be a downside, looked to pretty ;)
Will remove it again.

**Comment by elbotho** [comment]
PS: Thanks for keeping an eye on the bundle sizes!
 Could we maybe add this to CI to see how PRs will change bundles?

**Comment by elbotho** [comment]
(part of #852 now)

**Pull request closed without merging**
