### PR TITLE
refactor error handling

### LINKED ISSUE #1401: Refactor Error handling: use next approach
Follow up of #1391:

We should probably use the new ['notFound'](https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation) return and [next's custom error pages](https://nextjs.org/docs/advanced-features/custom-error-page#500-page)
 and maybe implement something like [this](https://victorthadeu-66076.medium.com/how-to-return-404-while-using-fallback-blocking-in-next-js-6fda63aad818).
 
Why:
- We should really not return status code 200 for 404 errors
- easier to understand if we follow the documented approach

### PR DESCRIPTION
**Pull request by Entkenntnis**
fixes #1401 

- use static 404 and 500 page.

(with serverless, if we are returning a 500 status code, we can'z pass any information to the error page. you can still see all messages in the deployment details)

### CODE REVIEW

**Comment by Entkenntnis** [comment]
Dynamic routes:

- `/[...slug]`: DONE
- `/entity/repository/compare/[entity_id]/[revision_id]`: DONE
- `/entity/repository/history/[id]`: nothing to do
- `/event/history/[...slug]`: DONE
- `/license/detail/[id]`: DONE
- `/user/[...userslug]`: DONE
- `/entity/repository/add-revision/[...id]` DONE

**Comment by Entkenntnis** [comment]
TODOs left:

- review changes
- test changes

**Comment by Entkenntnis** [comment]
one problem found: vercel is not rendering the custom error component, see https://github.com/vercel/next.js/discussions/32043

example: https://frontend-git-use-nextjs-error-handling-serlo.vercel.app/user/u

**Comment by Entkenntnis** [comment]
(side-note: maybe we need to handle this too: https://github.com/vercel/next.js/issues/8592)

**Comment by elbotho** [comment]
Would this still display on 500ers?
```
      temporary: "Die gute Nachricht? Das Problem scheint temporär zu sein, bitte versuch es später noch einmal.",
```

**Comment by Entkenntnis** [comment]
this page is for all 500er: https://frontend-git-use-nextjs-error-handling-serlo.vercel.app/500, so no.

But we can make the "temporary error" the default? Like: "try again later ..."

**Comment by elbotho** [comment]
So we don't get the actual error code?



500 | Internal Server Error (usually permanent)
… (rest probably temporary)
502 | Bad Gateway 
503 | Service Unavailable
504 | Gateway Timeout

**Comment by Entkenntnis** [comment]
Yep, all exceptions are 500 for serverless functions, at least atm

**Pull request merged**
