### PR TITLE
Some Refactoring

### LINKED ISSUE #781: Move license details into separate page
As far as I can see the license details page is not fetched as uuid, so we can move it to a separate page.

### PR DESCRIPTION
**Pull request by elbotho**
- fixed a bunch of react warnings 
- strict mode should now be active, but I could not find any warning, which makes me suspicious ;)  (for #783)
- license page is separate now (closes #781)
- split up fetch-page-data.ts

### CODE REVIEW

**Comment by Entkenntnis** [comment]
Experiencing a very weird issue: Vercel is not picking up the new page. Local build, and CI build are working as excepted.

???

**Comment by elbotho** [comment]
hmm, very weird, because e.g. the meta-title is set correctly. so fetch etc. seems to work. let me check something…

**Comment by elbotho** [comment]
Okay @Entkenntnis for some reason vercel still uses `[...slug]` to render this page. Could this be cached somewhere or something?

**Comment by Entkenntnis** [comment]
Jonas has asked on their slack, so see if there is a response.

**Comment by inyono** [comment]
Weird stuff. I'll let you know if I hear anything :)

**Comment by Entkenntnis** [comment]
@elbotho @inyono This was a perfect shot in the foot :grin:

**Comment by inyono** [comment]
Wow, awesome catch 😁

**Review by Entkenntnis — APPROVED** [review]
Thank you for the refactoring! Some surprises, like horizonData or transient props :+1:

**Comment by elbotho** [comment]
… oh boy 😅

**Pull request merged**
