### PR TITLE
bugfix: only show deleteOwnComment when the user is allowed to

### PR DESCRIPTION
**Pull request by MoeHome**
You are only able to delete a comment when it is an answer to another comment. But not if it is the start of a thread.

### CODE REVIEW

**Comment by MoeHome** [comment]
In the API it is possible to delete your own comment also, when it is the start of a thread if there are no answers to it or all the answers are yours. Is there a good way of implementing that here?

Edit: Actually I do have an idea.

**Comment by MoeHome** [comment]
And I don't know why the vercel error occurs.

**Review by Entkenntnis — APPROVED** [review]
thanks for the bugfix.

I have restarted vercel build and it should run fine now

**Comment by Entkenntnis** [comment]
I'll merge it, as it's a fix for staging

**Pull request merged**
