### PR TITLE
Remove Prisma package

### PR DESCRIPTION
**Pull request by shn-srl**
- Remove Prisma from frontend as it is no longer used

### CODE REVIEW

**Review by elbotho — APPROVED** [review]
thanks!

**Review by Entkenntnis — APPROVED** [review]
sad to see it go, though - was a nice enabler for quick stuff

**Comment by elbotho** [comment]
@Entkenntnis there is still
- https://turso.tech/
- https://neon.tech/ 
- https://www.cockroachlabs.com
- …

with free tiers. Sure they also might change their pricing models at some point but for experiment's I'm all for it 😀

**Comment by elbotho** [comment]
But maybe we can go with `drizzle` next time :)

**Pull request merged**
