### PR TITLE
refactor(editor): explicit React imports, class components

### PR DESCRIPTION
**Pull request by elbotho**
sorry for the PR spam, local builds and checks work fine and I'm trying to find the problem.

---- 
- used explicit React imports to merge code styles (not really necessary but…)
- refactored some old class components into functional components (the remaining class comps are special cases or quite big and need some testing)

### CODE REVIEW

**Comment by elbotho** [comment]
@Entkenntnis I have to conclude that this PR is cursed 👻, maybe you have an idea. 
Locally all checks work fine, but the gh actions throw errors that (I think) include old code.

**Review by Entkenntnis — APPROVED** [review]
thanks for cleaning up the code style

**Review by hejtful — APPROVED** [review]
Nice, thanks! In case you do something similar in the future, please feel free to remove the "internal", "public" and similar comments, these are leftovers from when edtr-io was supposed to be widely used

**Comment by elbotho** [comment]
> please feel free to remove the "internal", "public" and similar comments, these are leftovers from when edtr-io was supposed to be widely used

I will, thanks!

**Pull request merged**
