### PR TITLE
try periodical local autosave

### PR DESCRIPTION
**Pull request by elbotho**
for #2041

Basic idea:
- Für jede Revision die ein User im Editor öffnet speichern wir den State im localStorage
- Das speichern passiert automatisch (5 secs after last edit) (~fixed 10s interval for now since onChange requires more work~)
- Wenn vorhanden wird per infobox informiert, dass es eine gespeicherte Version gibt (mit datum + uhrzeit) die geladen werden kann (some improvement over alert).
- Wenn die Version geladen wurde kann User an gleicher Stelle auch seine Änderungen verwerfen

TODO:
- [x] cleanup UI
- [x] wording and i18n

### CODE REVIEW

**Comment by elbotho** [comment]
@Entkenntnis not finished but could you check the overal idea and flow?
I'll work on the rest when I'm a bit more rested.

`onChange` with a simple debounce would be a way nicer solution, but onChange is available in `SerloEditor` and the store is not so I implemented it this way for now.

**Comment by Entkenntnis** [comment]
Thank you for this PR - the overall flow is good.

Time-based is fine, if you want to use `onChange` you can use the `getDocument()` function, this should give you the serialized state (https://edtr.io/docs/getting-started#persisting-documents)

storing everything in one localstorage entry could be a bottleneck, because you have to parse everything again... I was also thinking about session storage as an option if it's enough for the use case

**Comment by elbotho** [comment]
> storing everything in one localstorage entry could be a bottleneck, because you have to parse everything again... I was also thinking about session storage as an option if it's enough for the use case

What difference between local- and sessionStorage are you refering to here?
Big downside to sessionStorage When the users browser is closed unintentionally or the system halts (or smth like that) all changes are still lost.

**Comment by elbotho** [comment]
> Time-based is fine, if you want to use onChange you can use the getDocument() function, this should give you the serialized state (https://edtr.io/docs/getting-started#persisting-documents)

Thanks for the link 👍

**Comment by elbotho** [comment]
@Entkenntnis ok ready from my side. Any more suggestions?
Otherwise I'd start testing this in staging.

**Review by Entkenntnis — APPROVED** [review]
thank you! you can start testing on staging

**Pull request merged**
