### PR TITLE
feat: call kratos api endpoint manually after registering

### PR DESCRIPTION
**Pull request by elbotho**
not the nicest code because I have to inject this into the kratos handler but this way it's only happening on the server side and we don't need an additional (unprotected) nextjs endpoint.

(currently not working because of missing secret)

So far it only took 28 new users 😅

### CODE REVIEW

**Comment by hugotiburtino** [comment]
I've tested locally and it worked. But we will have to see it in production, because the error is very hard to reproduce. 

Before deploying, we will have to synchronize, because we'll have to remove the webhook at kratos configuration at the same time.

**Review by hugotiburtino — APPROVED** [review]

**Comment by elbotho** [comment]
> I've tested locally and it worked. But we will have to see it in production, because the error is very hard to reproduce.

Nice! Happy to hear that.

> Before deploying, we will have to synchronize, because we'll have to remove the webhook at kratos configuration at the same time.

Is there a downside to having the endpoint being run twice for some time?

**Comment by elbotho** [comment]
we should probably have a sentry call here if the endpoint is not called

**Comment by hugotiburtino** [comment]
> Is there a downside to having the endpoint being run twice for some time?

Actually, it isn't a big deal, one of them is supposed to throw an error. I just want to avoid any kind of concurrence.
If the deployment has some minutes of delay, it's ok for me.

**Comment by elbotho** [comment]
@hugotiburtino actually I could not get it to work locally, but since it worked for you I'd merge this to staging to test, okay?

Hugo's edit: We are still testing locally

**Pull request merged**
