### PR TITLE
support scrolling to comment with anchor link

### PR DESCRIPTION
**Pull request by elbotho**
[example](https://frontend-git-scroll-to-comment.serlo.now.sh/mathe/1543/kathete#comment-124814)

notes:
- a bit complicated because of the lazy loading… (ping #800)
- also works with CSR
- hint: does not work on reload

### CODE REVIEW

**Comment by Entkenntnis** [comment]
Super cool feature. For me, it's working on reload.

To make this feature complete, we could:

- add entry to comment hover menu like "Link zu diesem Kommentar"
- add logic to cf worker that redirects ids to the proper path/hash link

**Review by Entkenntnis — APPROVED** [review]
Nice! Will merge after deployment. It took me some time to understand how "Link to this comment" works, though.

**Comment by elbotho** [comment]
> Nice! Will merge after deployment. It took me some time to understand how "Link to this comment" works, though.

yeah, maybe we need to rename that function… It was the easiest way to implement this for now. 
Or we do it like the function here on GitHub ("Copy Link")?

**Comment by Entkenntnis** [comment]
The github implementation looks quite straight forward.

**Comment by elbotho** [comment]
@Entkenntnis changed behaviour, also menu now closes after action.
(more annoying to implement than It should be ^^ be that's something I'll probably add to all menus now that we will rely on mutations more)

**Pull request merged**
