### PR TITLE
refactor link component

### LINKED ISSUE #2310: cleanup link component
remove some code for legacy serlo.

### PR DESCRIPTION
**Pull request by elbotho**
closes #2310 

@Entkenntnis I removed some `path` code since we don't use it currently. Okay with you?

### CODE REVIEW

**Comment by Entkenntnis** [comment]
removing `path` is fine

**Comment by elbotho** [comment]
@Entkenntnis Should I remove it everywhere then?

**Comment by Entkenntnis** [comment]
I think it was useful for e.g. revision view? Then we maybe need an alternative...

Edit: I'm not currently using it, so it's safe to remove.

**Review by Entkenntnis — APPROVED** [review]
Thank you for the refactoring, code looks good.

Some manuell testing an staging would be good here

**Comment by elbotho** [comment]
I remove it where we don't use it atm.

**Review by Entkenntnis — APPROVED** [review]
thanks

**Pull request merged**
