### PR TITLE
feat: enable users to delete their own comments

### PR DESCRIPTION
**Pull request by MoeHome**
issue in the API: https://github.com/serlo/api.serlo.org/issues/877

### CODE REVIEW

**Review by elbotho — APPROVED** [review]
nice one line PR 🙃

**Comment by elbotho** [comment]
Feature is not yet deployed in the API, correct?

**Comment by Entkenntnis** [comment]
I get this error: `You are not allowed to set the state of the provided comments(s).`

Otherwise a very elegant solution.

**Review by Entkenntnis — APPROVED** [review]
@MoeHome give me a notice as soon as change is deployed

**Comment by hugotiburtino** [comment]
pending because it is waiting for the deployment of api

**Comment by MoeHome** [comment]
> @MoeHome give me a notice as soon as change is deployed

It is now deployed in the API.

**Pull request merged**
