### PR TITLE
migrate edtr-io into frontend

### PR DESCRIPTION
**Pull request by Entkenntnis**
Merge package `@serlo/edtr-io` into the frontend and use it for add-revision.

Demo: https://frontend-git-edtr-io-serlo.vercel.app/entity/repository/add-revision/1585

### CODE REVIEW

**Comment by Entkenntnis** [comment]
will need https://github.com/serlo/frontend/pull/1212/commits/606569d132669ee0d2e24b0234eecf3d20af9f8c here as well

**Comment by elbotho** [comment]
@Entkenntnis write me on slack if I can support you here. Fixing types or smth.

**Comment by Entkenntnis** [comment]
no bundle size increase anymore - so technically this is mergable.

**Comment by elbotho** [comment]
@Entkenntnis we are now down to ~50 type errors. 

Prettier is also active in `external` now.
 
I also replaced the existing i18n implementation as inyono suggested. 
The translations are added, but I'll probably have to upload them again in staging.

**Comment by Entkenntnis** [comment]
thank you for this awesome work :100:

**Comment by Entkenntnis** [comment]
@elbotho I have fixed remaining errors are marked them with todo and already moved the code from `external`into `src`

**Comment by Entkenntnis** [comment]
continue work on staging

**Pull request merged**
