### PR TITLE
Add extra margin for extended settings

### PR DESCRIPTION
**Pull request by CodingDive**
This part of the editor is **very** confusing to me. A lot of render props for seemingly no reason. Had to use !important once to overwrite styled-component styles. I can refactor this soon but would like to get the small style changes in as soon as possible.
Btw: @GregorZupan has shown me today the new beautiful design that @elbotho and he came up with :nail_care: Therefore, this change will probably be completely unnecessary in a couple of weeks time when the new settings UI is implemented.

## Before

Screenshot from 2023-06-21 22-41-03

Screenshot from 2023-06-21 22-40-55

## After (with some more margins)

Screenshot from 2023-06-21 22-39-28

Screenshot from 2023-06-21 22-39-19

I may have missed some extended settings as I'm so new to the editor so please review carefully.

### CODE REVIEW

**Comment by elbotho** [comment]
@CodingDive you are correct, this will be replaced and this is the reason we did not put any work into it so far.
To be honest I will only accept this change if you base it on https://github.com/serlo/frontend/pull/2481 since file structure, i18n and other things changed.

**Comment by Entkenntnis** [comment]
@CodingDive please make sure the checks are successful before marking as ready for preview - this helps to reduce friction.

Otherwise I'm not sure if you are not done yet or there is a problem with the CI

**Comment by CodingDive** [comment]
Sorry, there was a big disconnect between my local environment and eslint
in CI. Will fix the warnings/errors but the code itself is ready for review.

**Comment by CodingDive** [comment]
**Locally**
image


**CI**
image


`yarn lint:prettier` also fails for me locally with following message (even after running yarn _prettier) 🤔 
image


Meanwhile `yarn lint:eslint` fails locally with a lot of errors too that are not showing up in the CI at all. 

image

**Review by Entkenntnis — CHANGES_REQUESTED** [review]
the multimedia-explanation plugin has changed in https://github.com/serlo/frontend/pull/2507, so parts of the PR are outdated now.

**Comment by CodingDive** [comment]
@Entkenntnis thanks for letting me know. I will fix all merge conflicts once it's merged into staging.

**Review by Entkenntnis — APPROVED** [review]
thank you, looks good

**Review by elbotho — APPROVED** [review]

**Pull request merged**
