### PR TITLE
fetch new quickbar data via proxy

### LINKED ISSUE #2550: use new quickbar updater data
- add proxy to avoid passing ip adress to github
- test for regressions (data should be the same)
- check for all occurences in the frontend (quickbar, editor)
- make sure response is gzipped

https://github.com/serlo/quickbar-updater is mostly complete now

### PR DESCRIPTION
**Pull request by Entkenntnis**
caching is a bit problematic, stick with cf-worker instead: https://github.com/serlo/cloudflare-worker/pull/439

### CODE REVIEW

**Comment by elbotho** [comment]
> caching is a bit problematic

Just curious :) 
What went wrong? too much or too little caching?

**Comment by Entkenntnis** [comment]
no support to cache `fetch` in api, so API would have to refetch every time, something like this ttl:

```
fetch(quickbarUrl, { cf: { cacheTtl: 24 * 60 * 60 } })
```

haven't really investigated it though ..

**Comment by elbotho** [comment]
for the future :) 
- [serverless](https://vercel.com/docs/concepts/functions/serverless-functions/edge-caching) 
- [or with edge](https://vercel.com/docs/concepts/functions/edge-functions/edge-caching)

**Comment by Entkenntnis** [comment]
I think we will switch to a frontend proxy when we add language versions, because otherwise it will be a bit annoying to sync the two implementations ..

**Pull request closed without merging**
