### PR TITLE
Add polyfill for hasown

### LINKED ISSUE #2042: Add polyfill for `Object.hasOwn`
It causes the problem

(edit: expanded logs)
```
instrument.ts:125 TypeError: Object.hasOwn is not a function
    at s (get-translated-type.ts:15)
    at subject-landing-featured.tsx:49
    at Array.map (<anonymous>)
    at O (subject-landing-featured.tsx:35)
    at ak (react-dom.production.min.js:168)
    at i (react-dom.production.min.js:291)
    at uI (react-dom.production.min.js:281)
    at react-dom.production.min.js:281
    at uO (react-dom.production.min.js:281)
    at u_ (react-dom.production.min.js:272)
    at ux (react-dom.production.min.js:269)
    at x (scheduler.production.min.js:14)
    at MessagePort.T (scheduler.production.min.js:15)
(anonymous) @ instrument.ts:125
instrument.ts:125 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
(anonymous) @ instrument.ts:125
instrument.ts:125 Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at i (react-dom.production.min.js:294)
    at uI (react-dom.production.min.js:281)
    at react-dom.production.min.js:281
    at uO (react-dom.production.min.js:281)
    at u_ (react-dom.production.min.js:272)
    at ux (react-dom.production.min.js:269)
    at x (scheduler.production.min.js:14)
    at MessagePort.T (scheduler.production.min.js:15)
(anonymous) @ instrument.ts:125
instrument.ts:125 Error rendering page:  Error: Cancel rendering route
    at l (index.js:405)
    at index.js:396
    at new Promise (<anonymous>)
    at es (index.js:394)
    at index.js:281
(anonymous) @ instrument.ts:125
DevTools failed to load SourceMap: Could not load content for https://sa.serlo.org/latest.js.map: Connection error: net::ERR_CONNECTION_CLOSED
```

which affects the a user that can't get newer Chrome updates , since her OS is quite outdated.

### PR DESCRIPTION
**Pull request by Entkenntnis**
source of polyfill: https://github.com/tc39/proposal-accessible-object-hasownproperty/blob/main/polyfill.js

### CODE REVIEW

**Comment by Entkenntnis** [comment]
ok, not sooo easy

**Comment by Entkenntnis** [comment]
@elbotho "Holzhammermethode", but it's simple and straight forward - remove in 3 - 4 years :)

**Comment by elbotho** [comment]
nice, did you test it already?

**Comment by Entkenntnis** [comment]
test results:

the earliest chrome that is working for us is chrome 71 (late 2018) - the original bug report was for chrome 84 and I successfully tested it.

chrome 70 - chrome 64 fail because we or one of the libraries is using some unsupported feature - but I think it's fine to leave it right now

**Comment by elbotho** [comment]
nice!

> chrome 70 - chrome 64 fail because we or one of the libraries is using some unsupported feature - but I think it's fine to leave it right now

you know what features? But I'm okay with that as well

**Review by elbotho — APPROVED** [review]
Thanks, also for the annoying testing 👍

**Pull request merged**
