### PR TITLE
editor: refactor spoiler

### PR DESCRIPTION
**Pull request by elbotho**
- shared renderer between frontend and editor
- improve styling

[example](https://frontend-git-refactor-spoiler-serlo.vercel.app/entity/repository/add-revision/1555)

### CODE REVIEW

**Review by Entkenntnis — APPROVED** [review]
looks good. I assume it's intended that you can't close the spoiler in editor?

**Comment by elbotho** [comment]
> I assume it's intended that you can't close the spoiler in editor?

Yes, after fiddling with focus stuff for a while I simplified to "open when active, closed when not" and nothing else for now.

**Comment by elbotho** [comment]
> looks good. I assume it's intended that you can't close the spoiler in editor?

Hmm thanks,
I think I intended it to close when not focused. I'll investigate again.

**Comment by Entkenntnis** [comment]
I find it actually less distracting if it always stays open, because we have less layout shifts - so I thought it was a feature :)

**Comment by elbotho** [comment]
well, I remember playing around with `focused` a bit and found it too unreliable (again)… so it's a feature after all 😂

**Pull request merged**
