### PR TITLE
Deployment

### PR DESCRIPTION
**Pull request by Entkenntnis**
- load geogebra without iframe: fix sizing
- fix e2e ci (using yarn now)
- dep upgrades
- editor: fix overlapped toolbar issue
- don't allow empty comments
- `/job/…` fix formating of lists
- editor: some fixes for refactored exercises

### CODE REVIEW

**Comment by Entkenntnis** [comment]
@elbotho if all checks succeed, we can deploy this right away (please approve otherwise I can't merge 😓)

**Comment by Entkenntnis** [comment]
Damn, Vercel has done some magic, build times are generally down to <2 min again 😮

**Comment by elbotho** [comment]
> (please approve otherwise I can't merge 😓)

I think you should be able to again 🎉

**Review by elbotho — APPROVED** [review]

**Comment by Entkenntnis** [comment]
I have set it up again ^^

**Pull request merged**
