### PR TITLE
WIP: quick font check helper

### PR DESCRIPTION
**Pull request by elbotho**

### CODE REVIEW

**Comment by elbotho** [comment]
[Karmilla (current)](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Karmilla)
[Source Sans Pro](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Source%20Sans%20Pro)
[Barlow](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Barlow)
[PT Sans](https://frontend-git-font-chooser.dal123.now.sh/1565?font=PT%20Sans)
[Poppins](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Poppins&spacing=0.02)
[Chivo](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Chivo)
[Archivo](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Archivo)
[Fira Sans](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Fira%20Sans)
[Noto Sans](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Noto%20Sans)
[Roboto](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Roboto)
[Public Sans](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Public%20Sans)
[HK Grotesk](https://frontend-git-font-chooser.dal123.now.sh/1565?font=HK%20Grotesk)
[Rubik](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Rubik)
[Work Sans](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Work%20Sans)
[Vremena Grotesk](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Vremena%20Grotesk)
[Nunito](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Nunito)
[Lato (khan ac)](https://frontend-git-font-chooser.dal123.now.sh/1565?font=Lato)

**Comment by elbotho** [comment]
btw: I love how quick something like this can be implemented now.
Would have never done this in athene :)

**Comment by elbotho** [comment]
(please don't merge)

**Comment by Entkenntnis** [comment]
OK, I've looked through the fonts. Here are some comments:

- Source Sanc Pro: lean, readable, letterspacing is better than Karmilla, active community, wide usage

- Noto Sans: very good language support, text color is darker than Source Sans Pro -> less difference between normal and bold

- Public Sans: comparable to Source Sans Pro, font is slightly bigger?

- Roboto: also very good quality

The other fonts seems to have smaller communities and/or are less readable / clear. Maybe I have overlooked a font, so this should not be a 'no' - but these four fonts are probably my favorites

**Comment by inyono** [comment]
Needs to be rebased onto master to work correctly with API v0.4.x

**Comment by Entkenntnis** [comment]
I will close this PR now (as the whole topic would need some more effort)

Preview stays online!

**Pull request closed without merging**
