### PR TITLE
first iteration of statistics dashboard

### LINKED ISSUE #2321: prototyping: dashboard
I have some ideas ...

### PR DESCRIPTION
**Pull request by Entkenntnis**
https://frontend-git-2321-prototyping-dashboard-serlo.vercel.app/___exercise_dashboard

### CODE REVIEW

**Comment by Entkenntnis** [comment]
closing - feature is complete, no merging in staging intented for the meantime

(keep branch)

**Comment by hugotiburtino** [comment]
Do you want to have a subdomain as alias for this branch?

**Comment by Entkenntnis** [comment]
not necessary for the moment - but can be part of another user story

**Comment by Entkenntnis** [comment]
needs some more tweaks

**Comment by Entkenntnis** [comment]
ok, from now on it should be stable

**Comment by Entkenntnis** [comment]
ok, another fix

**Comment by Entkenntnis** [comment]
some more fixing incoming

**Comment by Entkenntnis** [comment]
update completed

**Pull request closed without merging**
