### PR TITLE
Tailwind3 error

### PR DESCRIPTION
**Pull request by elbotho**
Migration to Tailwind 3 breaks builds. 
Could not find a solution so far so this is not part of the housekeeping PR.

It could be faulty class names or a problem with the postcss config?

```
info  - Creating an optimized production build ...<w> [webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/ … /frontend/node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[1]!/ … /frontend/node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[2].oneOf[8].use[2]!/ … /frontend/src/assets-webkit/styles/serlo-tailwind.css': No serializer registered for Warning
<w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> Array { 1 items } -> webpack/lib/ModuleWarning -> Warning
info  - Creating an optimized production build  
Failed to compile.

HookWebpackError: / … /frontend/static/css/<no source>:1:0: Unknown word
    at makeWebpackError (/ … /frontend/node_modules/next/dist/compiled/webpack/bundle5.js:41630:9)
    at / … /frontend/node_modules/next/dist/compiled/webpack/bundle5.js:25321:12
    at eval (eval at create (/ … /frontend/node_modules/next/dist/compiled/webpack/bundle5.js:140036:10), <anonymous>:44:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
-- inner error --
CssSyntaxError: / … /frontend/static/css/<no source>:1:0: Unknown word
    at Input.error (/ … /frontend/node_modules/postcss/lib/input.js:135:16)
    at ScssParser.unknownWord (/ … /frontend/node_modules/postcss/lib/parser.js:522:22)
    at ScssParser.other (/ … /frontend/node_modules/postcss/lib/parser.js:149:12)
    at ScssParser.parse (/ … /frontend/node_modules/postcss/lib/parser.js:59:16)
    at scssParse (/ … /frontend/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:322)
    at new LazyResult (/ … /frontend/node_modules/postcss/lib/lazy-result.js:133:16)
    at Processor.process (/ … /frontend/node_modules/postcss/lib/processor.js:28:14)
    at CssMinimizerPlugin.optimizeAsset (/ … /frontend/node_modules/next/dist/build/webpack/plugins/css-minimizer-plugin.js:43:12)
    at / … /frontend/node_modules/next/dist/build/webpack/plugins/css-minimizer-plugin.js:77:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
caused by plugins in Compilation.hooks.processAssets
CssSyntaxError: / … /frontend/static/css/<no source>:1:0: Unknown word
    at Input.error (/ … /frontend/node_modules/postcss/lib/input.js:135:16)
    at ScssParser.unknownWord (/ … /frontend/node_modules/postcss/lib/parser.js:522:22)
    at ScssParser.other (/ … /frontend/node_modules/postcss/lib/parser.js:149:12)
    at ScssParser.parse (/ … /frontend/node_modules/postcss/lib/parser.js:59:16)
    at scssParse (/ … /frontend/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:322)
    at new LazyResult (/ … /frontend/node_modules/postcss/lib/lazy-result.js:133:16)
    at Processor.process (/ … /frontend/node_modules/postcss/lib/processor.js:28:14)
    at CssMinimizerPlugin.optimizeAsset (/ … /frontend/node_modules/next/dist/build/webpack/plugins/css-minimizer-plugin.js:43:12)
    at / … /frontend/node_modules/next/dist/build/webpack/plugins/css-minimizer-plugin.js:77:55
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### CODE REVIEW

**Comment by Entkenntnis** [comment]
the error message is very undecriptive :/

One plugin that has always been problematic is "postcss-nested", it's now bundled with tailwind (see https://tailwindcss.com/docs/using-with-preprocessors#nesting) - maybe this could solve the issue.

the closest I can find is https://stackoverflow.com/questions/70466186/why-am-i-getting-this-error-tailwind-next-js-hookwebpackerror-csssyntaxerr

**Comment by elbotho** [comment]
Thanks @Entkenntnis for investigating.
This PR uses `tailwindcss/nesting` already.
I'll have another go at it once I updated all the other packages.

**Comment by elbotho** [comment]
@Entkenntnis 
Oh wow, that error reporting is really quite terrible. 
I ended up going through the folders (by only including them in the config) to find one of the problematic files and then classes. It turned out to be `shadow-menu`.

``` js
      boxShadow: {
        brand: `0 0 10px ${brand}, 0 0 5px ${brand}`,
        menu: 'rgba(0, 0, 0, 0.2) 0px 2px 4px;', //<-----------
        modal: '0px 0px 10px 0px rgba(0, 0, 0, 0.25)',
        input: `0 0 4px 0 ${brand}`,
      },
 ```
 
 Classic: Single semicolon breaks everything.

**Comment by Entkenntnis** [comment]
very nice catch :+1: - and very classic

**Pull request merged**
