### PR TITLE
fix(blanks-exercise): Make empty blanks not get deleted.

### PR DESCRIPTION
**Pull request by LarsTheGlidingSquirrel**
Fixes issue on iPad where a blank gets deleted even if there is content inside.

### CODE REVIEW

**Comment by CodingDive** [comment]
I guess this will work and fixes the bug, however the right approach would be to somehow keep the focus on the iPad but may not be that trivial.
Should we include a check to only do that for `isSafari()` or will that be too confusing to have a different behavior between Safari and Chrome browsers?

**Comment by LarsTheGlidingSquirrel** [comment]
> I guess this will work and fixes the bug, however the right approach would be to somehow keep the focus on the iPad but may not be that trivial. Should we include a check to only do that for `isSafari()` or will that be too confusing to have a different behavior between Safari and Chrome browsers?

In fact it, I saw it is not liked to Safari but the iPad. There the bug appears both on Safari & Chrome. I would recommend not implementing some platform specific logic unless we absolutely have to.

**Comment by LarsTheGlidingSquirrel** [comment]
Not fully happy with the solution, but it works as a quick fix for now. 
Things I would like to do differently: Get rid of `blanksWithCorrectAnswer` as it makes the code harder to understand. Remove empty blanks (and clean up) on save.

**Comment by elbotho** [comment]
> Not fully happy with the solution, but it works as a quick fix for now.
Things I would like to do differently: Get rid of blanksWithCorrectAnswer as it makes the code harder to understand. Remove empty blanks (and clean up) on save.

Agree. Moving complexity from the renderer to the editor is always preferable for me :)

**Review by elbotho — APPROVED** [review]
Seems to work well for me. Safari  on mac (ignoring some other inconsistencies) works fine as well.
Thank you for the quickfix.

**Pull request merged**
