### PR TITLE
Readd persistent layouts

### LINKED ISSUE #823: Persistent layouts with static property on page
Ups, after reading this https://adamwathan.me/2019/10/17/persistent-layout-patterns-in-nextjs/ (again) I think the best solution for us would be Option 3 or 4 with a static property on the component.

### LINKED ISSUE #829: rework data-types
Instead of initialprops, we now have a lot of different routes (with different props). Adapt the data types to reflect the new architecture.

### PR DESCRIPTION
**Pull request by Entkenntnis**
Will fix #823, #829.

Some interesting properties arise.

### CODE REVIEW

**Comment by Entkenntnis** [comment]
@elbotho This on is ready now. The main change is the function `renderedPageNoHooks` that takes a render function. Everything within this function can be persisted between pages. It's quite simple and types are working fine. The downside is that you can not use hooks in the function.

**Review by elbotho — APPROVED** [review]
Looks very nice,
and thanks for cleaning up the types!

**Comment by inyono** [comment]
>  The main change is the function `renderedPageNoHooks` that takes a render function. Everything within this function can be persisted between pages. It's quite simple and types are working fine. The downside is that you can not use hooks in the function.

What is the reason for passing the argument as a function (instead of a React component which would allow hooks etc.)?

**Comment by Entkenntnis** [comment]
Every page is a different component. Rendering with this component will remount everything within that component, including header + footer.

Example: Type something into the search input on the landing page and navigate to /mathe -> the search input is reset

**Comment by Entkenntnis** [comment]
You can still easily use hooks if you need to:

grafik

**Pull request merged**
