### PR TITLE
chore(community): Remove Wolfgang from CommunityWall (Team) 

### PR DESCRIPTION
**Pull request by CodingDive**
Do you prefer to just change his role from `Team` to `Autor` instead of removing him entirely?

### CODE REVIEW

**Comment by elbotho** [comment]
> Do you prefer to just change his role from Team to Autor instead of removing him entirely?

Hmm I think that's his call.

**Comment by CodingDive** [comment]
Will ask him and close in the meanwhile

**Comment by CodingDive** [comment]
He said he rather wants to be removed.

**Review by elbotho — APPROVED** [review]
😢

**Pull request merged**
