### PR TITLE
secondary navigation: placement and implementation

### LINKED ISSUE #6: Secondary navigation
2020-03-11-195454_221x456_scrot

### PR DESCRIPTION
**Pull request by Entkenntnis**
fixes #6 and #44

### CODE REVIEW

**Comment by Entkenntnis** [comment]
looks great so far

**Comment by Entkenntnis** [comment]
fixes #29 as well

**Comment by Entkenntnis** [comment]
@botho can you take a look at this (especially mobile menu). What do you think? We would probably need some more styling here ...

**Comment by elbotho** [comment]
@Entkenntnis jup I'd do some small things, you decide if here or in another branch.

**Pull request merged**
