### PR TITLE
Improve dev tooling, enforce stricter code style

### PR DESCRIPTION
**Pull request by inyono**
- `yarn lint` is the basic rule set that is enforced by CI (i.e. rules that are okay for prototyping). Might need to tweak the rules in the upcoming days depending on feedback. It allows to avoid type checking by basically placing an explicit `any` wherever. Contains some warnings that don't fail the CI but that should definitely be checked out since they are potentially problematic.
- `yarn lint:strict` is a stricter rule set that highlights parts of the code base that aren't typed well, yet (basically every place where we have `any` and didn't handle it in some way). This is the case in a lot of places right now (1637 errors, 170 warnings)! We might check that rule set also with CI in the future (for a subset of the code that isn't in prototype mode anymore)
- I added explicit `any`s with TODO comments at the places that failed TypeScript strict mode currently. These places should be refactored when we go over them next time.
- Gonna keep this open for feedback for a couple of days (you can skim the code changes and maybe check it out locally, note though, that most of the code changes where done automatically).
- I made some notes about potential problematic code that I saw when going over this. Gonna add issues for that so we can discuss those.

# Changelog

## Added

- Add command `yarn lint` that checks types, formatting and lint rules.
- Add command `yarn lint:strict` that contains a stricter lint rule set (highlighting current holes in our types).
- Add command `yarn format` that runs prettier and eslint with `--fix` flag.
- Add GitHub Actions to check lints and build.

# Changed

- Change license to Apache-2.0.
- Recommend the current LTS version of Node.js instead of >=10.
- Now → Vercel.
- Move `pages` into `src` (for simplified lint commands and consistent path mapping)
- Map `@` to `src` root.
- Enable TypeScript strict mode.
- Enable React strict mode.
- Make ESLint rule set stricter.
- Use kebab-case for file names consistently.

## Removed

- Remove `yarn prettify` in favor of `yarn format` (for consistency with other serlo.org projects).
- Remove `yarn typecheck` in favor of `yarn lint:tsc` (for consistency with other serlo.org projects).

### CODE REVIEW

**Comment by inyono** [comment]
#### 📝Changed routes:


| [**/.eslintrc**](https://frontend-git-strict.serlo.now.sh/.eslintrc) | [**/\[...slug\]**](https://frontend-git-strict.serlo.now.sh/[...slug]) |
|:-:|:-:|
|<a href="https://frontend-git-strict.serlo.now.sh/.eslintrc">Screenshot of /.eslintrc</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/aNQzR1Cx6HAbO0bNUmLmForEvLE_.png">(view full size)</a> |<a href="https://frontend-git-strict.serlo.now.sh/[...slug]">Screenshot of /[...slug]</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/gJEmaKhXGMneLKFjppnehXZ6Fro_.png">(view full size)</a> |



| [**/**](https://frontend-git-strict.serlo.now.sh/) | [**/search**](https://frontend-git-strict.serlo.now.sh/search) |
|:-:|:-:|
|<a href="https://frontend-git-strict.serlo.now.sh/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/dqqQOLWJpxNaKlU8_5BftChm6cQ_.png">(view full size)</a> |<a href="https://frontend-git-strict.serlo.now.sh/search">Screenshot of /search</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/pkiirURrSn4ujiBcQ7HB0YfAlSQ_.png">(view full size)</a> |



| [**/spenden**](https://frontend-git-strict.serlo.now.sh/spenden) |
|:-:|
|<a href="https://frontend-git-strict.serlo.now.sh/spenden">Screenshot of /spenden</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/4zh_hU3ILkfqGVt4uHG32JRoq78_.png">(view full size)</a> |



And 2 other routes:
- [**/api/frontend/\[...slug\]**](https://frontend-git-strict.serlo.now.sh/api/frontend/[...slug])
- [**/api/frontend/privacy**](https://frontend-git-strict.serlo.now.sh/api/frontend/privacy)

1 deleted route:
- **/api/frontend/privacy**

Commit 5b6284aec956a80ec6ef639a7c9e88cca4e81c4e (https://frontend-git-strict.serlo.now.sh).

**Comment by inyono** [comment]
@elbotho @Entkenntnis @kulla @theMetalkate Let me know if you have any veto against changing the license of your current contributions from MIT to Apache 2.0 (which is what we usually use for Serlo.org projects).

**Comment by Entkenntnis** [comment]
One note about filenames: All files in `/src/components/` are single React components and the file name always matches the component name (including casing). This helps me to navigate. I am fine with consistent kebap-casing in all other places, but I would like to keep the component-name = file-name schema within this one folder, especially as we have a lot of components.

**Comment by inyono** [comment]
> One note about filenames: All files in `/src/components/` are single React components and the file name always matches the component name (including casing). This helps me to navigate. I am fine with consistent kebap-casing in all other places, but I would like to keep the component-name = file-name schema within this one folder, especially as we have a lot of components.

I don't think that I understood this point. Do you mean that the filename `FooBar.tsx` improves the navigation over `foo-bar.tsx`? If there is only a single component in the file, the filename still matches the component name (except that that segments of the name aren't split by case but by a dash). VSCode & Webstorm both also support navigation by filename or symbol name out-of-the-box (e.g. in VSCode I can find a component `FooBar` regardless of the filename by symbol. Or I can look for the filename `foo-bar.tsx`).

For me, I see a couple of issues with such an exception:
- What about files that contain more than one component? It doesn't always make sense to have only one component per file (especially, if they are tightly related and/or only used privately and/or small). In this case, we'd have to change the casing.
- It makes the guideline more complicated. Kebab case is IMHO a good default guideline that works good for most programming languages (consistency). Because it's lowercase-only, it also prevents potential Git issues when changing the case of file names. It's also terminal-friendly (e.g. you can autocomplete for a segment of `foo-bar.tsx` but not in `FooBar.tsx` (pretty much what IDEs also do additionally for camel case).

**Comment by Entkenntnis** [comment]
It's more kind of a personal preference and *can potentially* reduce cognitive load while working - but you are right: On a technical level this is not quite defendable (at least I wouldn't try here)

So I would not block this PR because of this, but would be also quite happy if such an exception could be made...

**Comment by inyono** [comment]
In this case, I'd like to change it to kebab-case for the reasons listed above. My current approach for the Serlo.org guidelines / lint rules is basically:
- Make things as consistent as possible across projects (since we jump often between projects and also have a couple of community developers that come and go). Also, optimize for long-term productivity & changeability (that's one of the reasons I'm advocating for strict types)
- This is obviously not always possible. If there is an exception, there should be an objective reason for that (e.g. in the PHP code base we need to have PascalCase filenames matching exactly the classname because of the autoloader. But there is also a guarantee for a 1-on-1 mapping between files and classes, also because of autoloader).
- Push back personal preference as much as possible (that's why we have prettier & prettier-like tools in other programming languages since they just bring a good-enough and overly consistent formatting behavior), most of the choices we currently have in place started from "somewhere" but were adapted when we ran into problems.

I hope that's okay for you. Let me know if a guideline / lint rule doesn't work well. If there is a good reason to kick / change it, I'm all ears for it. And feel free to call me out on personal preference :)

**Comment by inyono** [comment]
If there aren't any more objections, I'll rebase/merge this over the weekend.

**Comment by kulla** [comment]
For me the current config is fine, since they are similar to the other repositories. I sometimes have the impression that a line width of 100 might be better. However [the warning at the prettier website](https://prettier.io/docs/en/options.html) convinced me that this might not be a good idea :see_no_evil:

**Comment by inyono** [comment]
superseded by #275

**Pull request closed without merging**
