### PR TITLE
prototype edtr.io in comments

### LINKED ISSUE #1175: More editing options for comments
Mandatory options:
- latex-formulas
- links
- bold, italic

Nice to haves
- colours
- lists
- ping other authors (more complex and would need more planning)
- Emojis

Btw. can we easily transfer the editing options for the text plug-in of edtr.io to comments?

### PR DESCRIPTION
**Pull request by elbotho**
### example
https://frontend-git-rich-comments-serlo.vercel.app/193389

### includes:
- working prototype
- some css-hacks to change the style of edtr.io children (might even be okay now that I just accepted the floating toolbar)

### TODO
- [x] resolve conflicts
- [ ] one type error I don't understand
- [ ] all strings in english, we could experiment with react-i18n-next integration
- [x] ~conversion should happen on server side -> extract fetch login into separate api route~ converter is reasonable small to be loaded on the client
- [x] only load edtr io when form is activated? -> comment form is dynamically loaded only for logged in user
- [x] fix tests
- [ ] problem with math input if using `strg-m` to insert element

### CODE REVIEW

**Comment by Entkenntnis** [comment]
Tested in locally right now - and it works :) ... but yes, there are some minor bugs, e.g. math formula rendering or missing translations.

**Comment by Entkenntnis** [comment]
(even auto-detect of pasted urls is working)

**Comment by elbotho** [comment]
> missing translations

Ah, good catch! Will have to find out how I can tell edtr what language to use.

**Comment by elbotho** [comment]
could you give me details/an example for the math formula rendering problem?
Seems to work for me.

**Comment by Entkenntnis** [comment]
@elbotho It was the bug when the css is missing and formulas are appearing twice - but I can't reproduce! Looks like a one-time quirk, I think we can ignore at atm ...

**Comment by elbotho** [comment]
- [ ] check how we can load this on demand only

**Comment by Entkenntnis** [comment]
the whole comment part of the application is already lazy loaded.

**Comment by elbotho** [comment]
> the whole comment part of the application is already lazy loaded.

true. My thinking: Most people won't acutally comment so they don't need to load the edtr.

**Comment by Entkenntnis** [comment]
Ah, right - we indeed need another level here

**Comment by Entkenntnis** [comment]
No work planned on this PR for the next 3-4 months, will focus on #1329 instead. (keep branch)

**Pull request closed without merging**
