### PR TITLE
fix(plugin-image): pixabay search vertical scroll bug on narrow screens

### PR DESCRIPTION
**Pull request by hejtful**
The actual fix is in the second commit.

In the first commit, I wanted to make it clear that the component doesn't only contain the button. Then after fixing the bug I thought it's also nice to split the big component.

[Demo link](https://frontend-git-fix-pixabay-search-modal-visual-bugs-serlo.vercel.app/___editor_preview?state=%7B%22plugin%22%3A%22rows%22%2C%22state%22%3A%5B%7B%22plugin%22%3A%22image%22%2C%22state%22%3A%7B%22src%22%3A%22%22%2C%22licence%22%3A%22Pixabay%22%2C%22caption%22%3A%7B%22plugin%22%3A%22text%22%2C%22state%22%3A%5B%7B%22type%22%3A%22p%22%2C%22children%22%3A%5B%7B%22text%22%3A%22%22%7D%5D%7D%5D%2C%22id%22%3A%2297d0fcf0-1c1c-4128-8825-9d98a541d989%22%7D%7D%2C%22id%22%3A%22f4569664-dc9d-4a55-ba08-86c46af1c1ab%22%7D%5D%7D) (You will have to choose Pixabay and resize the screen)

### CODE REVIEW

**Review by elbotho — APPROVED** [review]
Thank you, also for the refactoring.

One optional thing if you want to add it here: On small screens the popup should probably use the full height:
image

**Review by LarsTheGlidingSquirrel — APPROVED** [review]
Top margin behaves a little weird. But not a big issue. 
The important thing is the overlay is never cut off at the top any more. Thank you!

**Comment by hejtful** [comment]
@elbotho It took a bit more changes than expected to achieve it, but the modal uses more height on narrow screens now.

@LarsTheGlidingSquirrel If the modal's vertical positioning and usage of vertical space is what you meant by "Top margin behaves a little weird", that should be fixed now.

**Review by elbotho — APPROVED** [review]
Thank you, way better now.

**Pull request merged**
