### PR TITLE
Add consent functions

### LINKED ISSUE #778: Remember privacy consent and adding revoke option
We are currently not persisting the privacy conset, so closing the tab or opening a new tab will reset this information.

A slightly improved way to do this would be to store the consent on the client and add some information in our privacy agreement how to reset it, e.g. a special link

Edit: E.g. in localStorage for 14 days?

### PR DESCRIPTION
**Pull request by elbotho**
(closes #778)

### CODE REVIEW

**Comment by elbotho** [comment]
Okay working prototype online:
- watch a video (e.g. [here](https://frontend-git-remember-revoke-consent.serlo.vercel.app/community/74224/lernen-mit-serlo.org))
- navigate to the [new consent page](https://frontend-git-remember-revoke-consent.serlo.vercel.app/consent) via footer

@inyono could you have a look?

**Comment by Entkenntnis** [comment]
This already looks very promising.

For international users, we may need an english version as well, lets discuss this on monday.

**Comment by elbotho** [comment]
> For international users, we may need an english version as well, lets discuss this on monday.

sure, I'll add translations as soon as the privacy flow is @inyono approved ^^

**Comment by inyono** [comment]
> sure, I'll add translations as soon as the privacy flow is @inyono approved

I sent you sent feedback on Slack :)

**Comment by elbotho** [comment]
@Entkenntnis okay, ready for staging if you agree.

**Comment by elbotho** [comment]
(will add german texts back in through crowdin)

**Review by Entkenntnis — APPROVED** [review]
Very nice!

**Pull request merged**
