### PR TITLE
informatik landing page

### PR DESCRIPTION
**Pull request by elbotho**
Prototype for mostly automatically generated subject landing pages.

- Currently the content of the featured section is manually set (mainly because of the images)
- @Entkenntnis I made some changes to your quickbar to filter by subject and slightly improve the ux. I hope that is alright.

Demo:
https://frontend-git-subject-landing-pages-serlo.vercel.app/informatik

### CODE REVIEW

**Comment by hugotiburtino** [comment]
If I may point to something out in a PR which is still a draft, I noticed that the cursor sometimes do not recognize the link of the community user, for example
image

**Comment by elbotho** [comment]
@hugotiburtino thanks, fixed it but had not pushed yet.

**Comment by Entkenntnis** [comment]
thank you for featuring hack the web xD

**Comment by elbotho** [comment]
Only Info-Content I know and love :D

**Review by inyono — APPROVED** [review]
LGTM. The search bar could be a little bit wider on wider screens IMHO.

**Comment by elbotho** [comment]
Thanks @inyono!
Do you mean the popover or the whole thing?

**Comment by inyono** [comment]
The popover. Only making the popover wider would also look weird, I guess. Just my 2 cents, do with that feedback whatever you want 😬

**Review by Entkenntnis — APPROVED** [review]
the changes with the quickbar are fine!

**Comment by elbotho** [comment]
landing pages for all subjects in #1468

**Pull request closed without merging**
