### PR TITLE
hotfix: revert change because it breaks legacy saving

### PR DESCRIPTION
**Pull request by elbotho**
course pages can not be saved atm. via the legacy infrastructure. 

@Entkenntnis do you mind if I deploy this or could you?

### CODE REVIEW

**Review by Entkenntnis — APPROVED** [review]
fix looks reasonable! let's deploy this.

**Comment by elbotho** [comment]
@Entkenntnis  Sorry I set it up wrong, it's in staging now – not production.

**Comment by elbotho** [comment]
Also: staging is down right now, I don't know if this affects deployment.

**Comment by Entkenntnis** [comment]
Yeah, I wanted to cherry-pick this into production - but without staging, it's probably difficult to deploy (tests are failing ...)

**Pull request merged**
