### PR TITLE
Show comments

### LINKED ISSUE #492: Load comments
We need to fetch comments from the server, so we can show them in #465.

### PR DESCRIPTION
**Pull request by Entkenntnis**
It's cool to have threads available in the API! This PR adds basic support for them in the frontend.

Take a look: https://frontend-git-comments.serlo.now.sh/2055 (scroll down)

Fixes #492

### CODE REVIEW

**Comment by elbotho** [comment]
Nice!

**Comment by Entkenntnis** [comment]
Small todos:

- Check why comments are not loaded for https://frontend-git-comments.serlo.now.sh/informatik/baustelle/93611 (exercise group, id 93611)
- and https://frontend-git-comments.serlo.now.sh/community/sandkasten/methodenkiste/wissenschaftliches-denken-arbeiten/motivation:-kleines-experiment (course, id 179596)

@CarolinJaser Could you take a look at this two? I am getting "There are no comments yet" errors, but on production, the comments are existing.

**Comment by inyono** [comment]
Regarding 93611 / 179596: Both return one thread for me:
```graphql
{
  uuid(id:93611) { # Resp. 179596
    __typename
    ... on AbstractUuid {
      threads {
        totalCount
      }
    }
  }
}
```

**Comment by inyono** [comment]
Most likely a caching issue since we don't have listeners for that in place, yet. I'll review the SWR maxAge times for stuff that changes.

**Comment by Entkenntnis** [comment]
Can confirm, both pages are working now, seems to be related to SWR maxAge ...

**Pull request merged**
