### PR TITLE
Deployment

### PR DESCRIPTION
**Pull request by Entkenntnis**
- Bugfixes
- profile: add custom message to **chat invites** (in testing atm.)
- new version of **fontawesome** (some icons changed)
- improved **box plugin** (new edtr version with bugfixes, custom plugin selections)

### CODE REVIEW

**Comment by Entkenntnis** [comment]
Dependencies are a mystery: updating fontawesome has resulted in a +10kb bundle size increase - I will take a look into this ...

**Comment by elbotho** [comment]
> updating fontawesome

I updated because `edtr-io` updated and the mismatched versions causes some troubles with types.

**Comment by Entkenntnis** [comment]
unfortunately not much we can do here. version 6 adds a lot of features that are not tree shaken. I have opened an issue for this: #1552

**Comment by elbotho** [comment]
just a heads up, I thought I messed up the subject landing page code, but it seems on staging the math tree got a lot of pruning: https://de.serlo-staging.dev/mathe
Not sure what happened there.

**Comment by Entkenntnis** [comment]
well, somebody deleted a lot of folders :eyes: should be back by tomorrow ...

@elbotho is this PR ready for deployment on monday? contains a good bunch of fixes

**Comment by elbotho** [comment]
the personalised chat invite is not tested very well.
(but it's also not critical)

**Comment by Entkenntnis** [comment]
I have tested the invite feature a bit and it's working

**Pull request merged**
