### PR TITLE
Add profile image to discussions

### PR DESCRIPTION
**Pull request by kulla**
2021-04-16-135036_464x323_scrot

### CODE REVIEW

**Comment by elbotho** [comment]
Nice, very simple. 
I have some small design changes. Should I comment or take over?

**Comment by kulla** [comment]
> I have some small design changes. Should I comment or take over?

Take over :smile:

**Review by elbotho — APPROVED** [review]
Okay, changed some details and made the images completely round.
@kulla if you agree with the changes this can be merged.

**Comment by Entkenntnis** [comment]
Looks very nice! Thank you two!

**Pull request merged**
