### PR TITLE
next 12, upgrades, …

### PR DESCRIPTION
**Pull request by elbotho**

### CODE REVIEW

**Comment by Entkenntnis** [comment]
bundle size increased to 153kb  ... it looks like _app is always bundled but I haven't investigated it yet.

**Comment by elbotho** [comment]
> bundle size increased to 153kb 

As always, thanks for keeping an eye on that.

**Comment by elbotho** [comment]
this branch: `153kb`
without `swcMinify`: `148kb`
current main: `144kb`

**Comment by Entkenntnis** [comment]
related: https://github.com/vercel/next.js/discussions/30237

**Comment by elbotho** [comment]
with `12.02` and `swcMinify: false` we are at `147kb`
the `3kb` might just be new code I guess.
@Entkenntnis should we merge it or wait for further improvements?

**Comment by Entkenntnis** [comment]
looks fine, we can investigate bundle size increase later

**Pull request merged**
