### PR TITLE
editor: tab change bug

### PR DESCRIPTION
**Pull request by elbotho**

### CODE REVIEW

**Review by Entkenntnis — CHANGES_REQUESTED** [review]
#2027 would hopefully fix the root cause

**Comment by elbotho** [comment]
> https://github.com/serlo/frontend/pull/2027 would hopefully fix the root cause

🎉 it did. If you don't mind I would merge https://github.com/serlo/frontend/pull/2025/commits/a077b9312e96890ad170ea287187cfab6a81fc54 to staging just to make to a bit more secure.

**Comment by Entkenntnis** [comment]
yes, you can merge this extra check, won't hurt

**Comment by elbotho** [comment]
> yes, you can merge this extra check, won't hurt

You already did, right?

**Pull request closed without merging**
